### ISSUE TITLE
jest's globals are breaking the tests

### ISSUE THREAD

**Issue by radiovisual** [radiovisual/generator-nmx#6]
<pre>
> generator-nmx@1.0.1 test /Users/michael/gitprojects/generator-nmx
> xo && ava

module.js:471
    throw err;
    ^

Error: Cannot find module '../<% if (babel) { %>dist/<% } %>'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michael/gitprojects/generator-nmx/app/templates/__tests__/test.js:1:1)
    at Module._compile (module.js:570:32)
    at extensions.(anonymous function) (/Users/michael/gitprojects/generator-nmx/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michael/gitprojects/generator-nmx/node_modules/ava/lib/process-adapter.js:105:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michael/gitprojects/generator-nmx/node_modules/ava/lib/test-worker.js:33:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
/Users/michael/gitprojects/generator-nmx/temp/__tests__/test.js:9
test('title', () => {
^

ReferenceError: test is not defined
    at Object.<anonymous> (/Users/michael/gitprojects/generator-nmx/temp/__tests__/test.js:3:1)
    at Module._compile (module.js:570:32)
    at extensions.(anonymous function) (/Users/michael/gitprojects/generator-nmx/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/michael/gitprojects/generator-nmx/node_modules/ava/lib/process-adapter.js:105:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michael/gitprojects/generator-nmx/node_modules/ava/lib/test-worker.js:33:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
</pre>

**Comment by radiovisual** [comment]
I will get to this when I have some time. Until then, Pull requests are welcome.
